import os
import requests
from dotenv import load_dotenv


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALERTS_PATH = os.path.join(BASE_DIR, "reports", "telegram_alerts.md")

load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")


def load_alert_message() -> str:
    """
    Loads the Telegram alert message generated by the quant engine.
    """

    if not os.path.exists(ALERTS_PATH):
        raise FileNotFoundError(
            f"Telegram alerts file not found: {ALERTS_PATH}. "
            "Run python src/main.py first."
        )

    with open(ALERTS_PATH, "r", encoding="utf-8") as file:
        return file.read()


def send_telegram_message(message: str):
    """
    Sends a message to Telegram using the Bot API.
    """

    if not TELEGRAM_BOT_TOKEN:
        raise ValueError("Missing TELEGRAM_BOT_TOKEN in .env")

    if not TELEGRAM_CHAT_ID:
        raise ValueError("Missing TELEGRAM_CHAT_ID in .env")

    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"

    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": message[:4000],
        "parse_mode": "Markdown",
    }

    response = requests.post(url, json=payload, timeout=15)

    if response.status_code != 200:
        raise RuntimeError(
            f"Telegram API error: {response.status_code} - {response.text}"
        )

    print("Telegram alert sent successfully.")


def main():
    message = load_alert_message()
    send_telegram_message(message)


if __name__ == "__main__":
    main()