import os
import pandas as pd


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROCESSED_DIR = os.path.join(BASE_DIR, "data", "processed")
REPORTS_DIR = os.path.join(BASE_DIR, "reports")

PICK_HISTORY_PATH = os.path.join(PROCESSED_DIR, "pick_history.csv")
PERFORMANCE_SUMMARY_PATH = os.path.join(REPORTS_DIR, "performance_summary.md")


def calculate_performance_metrics(history: pd.DataFrame) -> dict:
    """
    Calculates basic performance metrics from pick_history.csv.

    PENDING picks are not included in win/loss/ROI metrics.
    """

    total_picks = len(history)
    open_picks = len(history[history["status"] == "OPEN"])
    settled_picks = history[history["status"] == "CLOSED"].copy()

    total_settled = len(settled_picks)

    won = len(settled_picks[settled_picks["result"] == "WON"])
    lost = len(settled_picks[settled_picks["result"] == "LOST"])
    push = len(settled_picks[settled_picks["result"] == "PUSH"])

    if total_settled > 0:
        hit_rate = won / total_settled
        total_profit_loss = settled_picks["profit_loss_units"].sum()
        total_staked = settled_picks["stake_pct"].sum()

        if total_staked > 0:
            roi = total_profit_loss / total_staked
        else:
            roi = 0
    else:
        hit_rate = 0
        total_profit_loss = 0
        total_staked = 0
        roi = 0

    average_value_gap = history["value_gap"].mean() if total_picks > 0 else 0
    average_confidence_score = history["confidence_score"].mean() if total_picks > 0 else 0

    return {
        "total_picks": total_picks,
        "open_picks": open_picks,
        "settled_picks": total_settled,
        "won": won,
        "lost": lost,
        "push": push,
        "hit_rate": hit_rate,
        "total_profit_loss": total_profit_loss,
        "total_staked": total_staked,
        "roi": roi,
        "average_value_gap": average_value_gap,
        "average_confidence_score": average_confidence_score,
    }


def generate_performance_summary():
    """
    Generates a Markdown summary of tracked model performance.
    """

    os.makedirs(REPORTS_DIR, exist_ok=True)

    if not os.path.exists(PICK_HISTORY_PATH):
        lines = [
            "# World Cup Quant Performance Summary",
            "",
            "No pick history found yet.",
            "",
            "Run the pipeline first to generate pick history.",
        ]

        with open(PERFORMANCE_SUMMARY_PATH, "w", encoding="utf-8") as file:
            file.write("\n".join(lines))

        print(f"Performance summary generated: {PERFORMANCE_SUMMARY_PATH}")
        return

    history = pd.read_csv(PICK_HISTORY_PATH)
    metrics = calculate_performance_metrics(history)

    lines = []

    lines.append("# World Cup Quant Performance Summary")
    lines.append("")
    lines.append("## Model Tracking Overview")
    lines.append("")
    lines.append(
        "This summary tracks all value signals generated by the model. "
        "Open picks are not counted in win/loss or ROI metrics until settled."
    )
    lines.append("")

    lines.append("## Core Metrics")
    lines.append("")
    lines.append(f"- Total picks tracked: **{metrics['total_picks']}**")
    lines.append(f"- Open picks: **{metrics['open_picks']}**")
    lines.append(f"- Settled picks: **{metrics['settled_picks']}**")
    lines.append(f"- Won: **{metrics['won']}**")
    lines.append(f"- Lost: **{metrics['lost']}**")
    lines.append(f"- Push: **{metrics['push']}**")
    lines.append(f"- Hit rate: **{metrics['hit_rate']:.2%}**")
    lines.append(f"- Total profit/loss units: **{metrics['total_profit_loss']:.4f}**")
    lines.append(f"- ROI: **{metrics['roi']:.2%}**")
    lines.append("")

    lines.append("## Signal Quality")
    lines.append("")
    lines.append(f"- Average value gap: **{metrics['average_value_gap']:.2%}**")
    lines.append(f"- Average confidence score: **{metrics['average_confidence_score']:.2%}**")
    lines.append("")

    lines.append("## Important Note")
    lines.append("")
    lines.append(
        "These metrics are for transparency and model tracking only. "
        "Past performance does not guarantee future results. "
        "Betting involves risk."
    )

    with open(PERFORMANCE_SUMMARY_PATH, "w", encoding="utf-8") as file:
        file.write("\n".join(lines))

    print(f"Performance summary generated: {PERFORMANCE_SUMMARY_PATH}")