import os


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LANDING_DIR = os.path.join(BASE_DIR, "landing")
PRICING_STRATEGY_PATH = os.path.join(LANDING_DIR, "pricing_strategy.md")


def generate_pricing_strategy():
    """
    Generates a pricing and monetization strategy for the World Cup Quant product.
    """

    lines = []

    lines.append("# World Cup Quant Pricing Strategy")
    lines.append("")
    lines.append("## Revenue Goal")
    lines.append("")
    lines.append("Target: **USD $10,000** during the World Cup 2026 campaign.")
    lines.append("")
    lines.append("This should not depend on personal betting profit. The main business model is selling:")
    lines.append("")
    lines.append("- betting intelligence")
    lines.append("- model probabilities")
    lines.append("- value gap analysis")
    lines.append("- risk labels")
    lines.append("- bankroll discipline notes")
    lines.append("- Telegram alerts")
    lines.append("- premium CSV/report access")
    lines.append("")

    lines.append("## Core Positioning")
    lines.append("")
    lines.append("Do not sell this as guaranteed picks.")
    lines.append("")
    lines.append("Sell it as:")
    lines.append("")
    lines.append("> Data-driven World Cup betting intelligence for people who want to compare price vs probability.")
    lines.append("")

    lines.append("## Recommended Offer Ladder")
    lines.append("")

    lines.append("### 1. Free Quant Brief")
    lines.append("")
    lines.append("Price: **Free**")
    lines.append("")
    lines.append("Purpose: audience growth and email capture.")
    lines.append("")
    lines.append("Includes:")
    lines.append("- 1 public data signal")
    lines.append("- simple explanation")
    lines.append("- responsible betting note")
    lines.append("- CTA to premium access")
    lines.append("")

    lines.append("### 2. Early Access")
    lines.append("")
    lines.append("Suggested price: **$49**")
    lines.append("")
    lines.append("Purpose: validate demand before the tournament.")
    lines.append("")
    lines.append("Includes:")
    lines.append("- premium CSV")
    lines.append("- daily written brief")
    lines.append("- model probabilities")
    lines.append("- value gaps")
    lines.append("- risk labels")
    lines.append("- confidence scores")
    lines.append("- bankroll notes")
    lines.append("")
    lines.append("Revenue math:")
    lines.append("")
    lines.append("```text")
    lines.append("20 sales x $49 = $980")
    lines.append("30 sales x $49 = $1,470")
    lines.append("50 sales x $49 = $2,450")
    lines.append("```")
    lines.append("")

    lines.append("### 3. Premium Tournament Pass")
    lines.append("")
    lines.append("Suggested price: **$99**")
    lines.append("")
    lines.append("Purpose: main product.")
    lines.append("")
    lines.append("Includes:")
    lines.append("- everything in Early Access")
    lines.append("- Telegram alerts")
    lines.append("- daily premium report")
    lines.append("- performance tracking summary")
    lines.append("- upset tracker")
    lines.append("- bankroll guide")
    lines.append("")
    lines.append("Revenue math:")
    lines.append("")
    lines.append("```text")
    lines.append("50 sales x $99 = $4,950")
    lines.append("75 sales x $99 = $7,425")
    lines.append("102 sales x $99 = $10,098")
    lines.append("```")
    lines.append("")

    lines.append("### 4. Full World Cup Quant Bundle")
    lines.append("")
    lines.append("Suggested price: **$149**")
    lines.append("")
    lines.append("Purpose: higher-ticket offer.")
    lines.append("")
    lines.append("Includes:")
    lines.append("- full tournament access")
    lines.append("- daily reports")
    lines.append("- Telegram alerts")
    lines.append("- premium CSV updates")
    lines.append("- weekly recap")
    lines.append("- model explanation")
    lines.append("- bankroll guide")
    lines.append("- performance tracking")
    lines.append("")
    lines.append("Revenue math:")
    lines.append("")
    lines.append("```text")
    lines.append("25 sales x $149 = $3,725")
    lines.append("50 sales x $149 = $7,450")
    lines.append("68 sales x $149 = $10,132")
    lines.append("```")
    lines.append("")

    lines.append("## Best Starting Strategy")
    lines.append("")
    lines.append("Do not launch with too many products.")
    lines.append("")
    lines.append("Start with one simple offer:")
    lines.append("")
    lines.append("```text")
    lines.append("World Cup Quant Early Access — $49")
    lines.append("```")
    lines.append("")
    lines.append("Then increase price when there is:")
    lines.append("")
    lines.append("- consistent content")
    lines.append("- email list growth")
    lines.append("- public samples")
    lines.append("- tracked performance")
    lines.append("- better product packaging")
    lines.append("")

    lines.append("## Recommended Price Timeline")
    lines.append("")
    lines.append("### Phase 1 — Build Audience")
    lines.append("")
    lines.append("Price: **Free**")
    lines.append("")
    lines.append("Goal:")
    lines.append("- publish free signals")
    lines.append("- collect emails")
    lines.append("- build credibility")
    lines.append("- track performance")
    lines.append("")

    lines.append("### Phase 2 — Early Access")
    lines.append("")
    lines.append("Price: **$49**")
    lines.append("")
    lines.append("Goal:")
    lines.append("- first 20-50 buyers")
    lines.append("- validate that people pay")
    lines.append("- collect feedback")
    lines.append("")

    lines.append("### Phase 3 — Tournament Launch")
    lines.append("")
    lines.append("Prices:")
    lines.append("- Standard: **$79**")
    lines.append("- Premium: **$149**")
    lines.append("")
    lines.append("Goal:")
    lines.append("- monetize urgency during the tournament")
    lines.append("- sell daily intelligence, not generic analysis")
    lines.append("")

    lines.append("## Path to $10k")
    lines.append("")
    lines.append("Possible scenario:")
    lines.append("")
    lines.append("```text")
    lines.append("30 Early Access sales x $49 = $1,470")
    lines.append("40 Premium sales x $149 = $5,960")
    lines.append("30 Standard sales x $79 = $2,370")
    lines.append("-----------------------------------")
    lines.append("Total = $9,800")
    lines.append("```")
    lines.append("")
    lines.append("Another scenario:")
    lines.append("")
    lines.append("```text")
    lines.append("68 Full Bundle sales x $149 = $10,132")
    lines.append("```")
    lines.append("")

    lines.append("## What Actually Drives Sales")
    lines.append("")
    lines.append("The model alone does not sell.")
    lines.append("")
    lines.append("Sales come from:")
    lines.append("")
    lines.append("- trust")
    lines.append("- daily content")
    lines.append("- clear examples")
    lines.append("- transparent tracking")
    lines.append("- simple explanations")
    lines.append("- urgency during the tournament")
    lines.append("- responsible positioning")
    lines.append("")

    lines.append("## What Not To Promise")
    lines.append("")
    lines.append("Never say:")
    lines.append("")
    lines.append("- guaranteed wins")
    lines.append("- risk-free betting")
    lines.append("- beat the bookies")
    lines.append("- make money easily")
    lines.append("- sure picks")
    lines.append("")
    lines.append("Use safer language:")
    lines.append("")
    lines.append("- model signal")
    lines.append("- possible value gap")
    lines.append("- price vs probability")
    lines.append("- risk-aware analysis")
    lines.append("- educational betting intelligence")
    lines.append("")

    lines.append("## Immediate Action Plan")
    lines.append("")
    lines.append("Before selling, build these assets:")
    lines.append("")
    lines.append("1. Free sample report")
    lines.append("2. Performance summary")
    lines.append("3. Landing page")
    lines.append("4. Email capture")
    lines.append("5. Telegram channel")
    lines.append("6. Payment link")
    lines.append("7. Daily content schedule")
    lines.append("")

    lines.append("## Brutal Reminder")
    lines.append("")
    lines.append("If the system generates reports but nobody sees them, revenue is $0.")
    lines.append("")
    lines.append("Distribution is now as important as the model.")

    os.makedirs(LANDING_DIR, exist_ok=True)

    with open(PRICING_STRATEGY_PATH, "w", encoding="utf-8") as file:
        file.write("\n".join(lines))

    print(f"Pricing strategy generated: {PRICING_STRATEGY_PATH}")